import type { StandardPose } from '@/types/pose'

export const STANDARD_POSES: StandardPose[] = [
  {
    id: 'tadasana',
    nameCN: '山式',
    nameEN: 'Mountain Pose',
    nameSanskrit: 'Tadasana',
    difficulty: 'beginner',
    category: '站立',
    description: '双脚并拢站立，身体挺直，双臂自然下垂',
    benefits: ['改善体态', '增强腿部力量', '提高平衡感'],
    targetAngles: [
      { joint: 'left_knee', angle: 175, axis: 'flexion' },
      { joint: 'right_knee', angle: 175, axis: 'flexion' },
      { joint: 'left_hip', angle: 175, axis: 'flexion' },
      { joint: 'right_hip', angle: 175, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 10, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 10, axis: 'abduction' },
    ],
    tolerance: 15,
    keyPoints: [
      { joint: 'left_knee', idealAngle: 175, description: '膝盖伸直，不要超伸' },
      { joint: 'right_knee', idealAngle: 175, description: '膝盖伸直，不要超伸' },
    ],
    commonMistakes: ['膝盖超伸', '骨盆前倾', '耸肩'],
  },
  {
    id: 'virabhadrasana_ii',
    nameCN: '战士二式',
    nameEN: 'Warrior II',
    nameSanskrit: 'Virabhadrasana II',
    difficulty: 'beginner',
    category: '站立',
    description: '双腿分开，前膝弯曲90度，双臂平举',
    benefits: ['增强腿部力量', '打开髋部', '提高专注力'],
    targetAngles: [
      { joint: 'left_knee', angle: 90, axis: 'flexion' },
      { joint: 'right_knee', angle: 175, axis: 'flexion' },
      { joint: 'left_hip', angle: 90, axis: 'flexion' },
      { joint: 'right_hip', angle: 135, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 90, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 90, axis: 'abduction' },
    ],
    tolerance: 20,
    keyPoints: [
      { joint: 'left_knee', idealAngle: 90, description: '前膝保持90度弯曲' },
      { joint: 'left_shoulder', idealAngle: 90, description: '双臂平举与地面平行' },
    ],
    commonMistakes: ['前膝超过脚尖', '后脚跟离地', '身体前倾'],
  },
  {
    id: 'trikonasana',
    nameCN: '三角式',
    nameEN: 'Triangle Pose',
    nameSanskrit: 'Trikonasana',
    difficulty: 'beginner',
    category: '站立',
    description: '双腿分开，身体侧弯，一手触地',
    benefits: ['拉伸侧腰', '增强腿部力量', '改善平衡'],
    targetAngles: [
      { joint: 'left_knee', angle: 175, axis: 'flexion' },
      { joint: 'right_knee', angle: 175, axis: 'flexion' },
      { joint: 'left_hip', angle: 120, axis: 'flexion' },
      { joint: 'right_hip', angle: 120, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 160, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 20, axis: 'abduction' },
    ],
    tolerance: 20,
    keyPoints: [
      { joint: 'left_knee', idealAngle: 175, description: '双腿保持伸直' },
    ],
    commonMistakes: ['膝盖弯曲', '身体前倾而非侧弯', '耸肩'],
  },
  {
    id: 'adho_mukha_svanasana',
    nameCN: '下犬式',
    nameEN: 'Downward Dog',
    nameSanskrit: 'Adho Mukha Svanasana',
    difficulty: 'beginner',
    category: '倒置',
    description: '倒V形，手臂和腿伸直',
    benefits: ['拉伸全身', '增强手臂力量', '改善血液循环'],
    targetAngles: [
      { joint: 'left_knee', angle: 175, axis: 'flexion' },
      { joint: 'right_knee', angle: 175, axis: 'flexion' },
      { joint: 'left_hip', angle: 90, axis: 'flexion' },
      { joint: 'right_hip', angle: 90, axis: 'flexion' },
      { joint: 'left_elbow', angle: 175, axis: 'flexion' },
      { joint: 'right_elbow', angle: 175, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 160, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 160, axis: 'abduction' },
    ],
    tolerance: 20,
    keyPoints: [
      { joint: 'left_hip', idealAngle: 90, description: '髋部折叠约90度' },
      { joint: 'left_elbow', idealAngle: 175, description: '手臂伸直' },
    ],
    commonMistakes: ['拱背', '膝盖弯曲', '头部下垂'],
  },
  {
    id: 'vrksasana',
    nameCN: '树式',
    nameEN: 'Tree Pose',
    nameSanskrit: 'Vrksasana',
    difficulty: 'beginner',
    category: '平衡',
    description: '单腿站立，一脚抵大腿内侧',
    benefits: ['提高平衡感', '增强腿部力量', '培养专注力'],
    targetAngles: [
      { joint: 'left_knee', angle: 175, axis: 'flexion' },
      { joint: 'right_knee', angle: 45, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 160, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 160, axis: 'abduction' },
    ],
    tolerance: 25,
    keyPoints: [
      { joint: 'left_knee', idealAngle: 175, description: '支撑腿伸直' },
    ],
    commonMistakes: ['身体晃动', '骨盆倾斜', '脚抵在膝盖上'],
  },
  {
    id: 'utkatasana',
    nameCN: '幻椅式',
    nameEN: 'Chair Pose',
    nameSanskrit: 'Utkatasana',
    difficulty: 'beginner',
    category: '站立',
    description: '膝弯曲90度，双臂上举',
    benefits: ['增强腿部力量', '激活核心', '改善体态'],
    targetAngles: [
      { joint: 'left_knee', angle: 90, axis: 'flexion' },
      { joint: 'right_knee', angle: 90, axis: 'flexion' },
      { joint: 'left_hip', angle: 90, axis: 'flexion' },
      { joint: 'right_hip', angle: 90, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 170, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 170, axis: 'abduction' },
    ],
    tolerance: 20,
    keyPoints: [
      { joint: 'left_knee', idealAngle: 90, description: '膝盖保持90度弯曲' },
    ],
    commonMistakes: ['膝盖超过脚尖', '腰部塌陷', '手臂下垂'],
  },
  {
    id: 'balasana',
    nameCN: '婴儿式',
    nameEN: "Child's Pose",
    nameSanskrit: 'Balasana',
    difficulty: 'beginner',
    category: '跪姿',
    description: '跪坐，身体前屈',
    benefits: ['放松全身', '缓解压力', '拉伸背部'],
    targetAngles: [
      { joint: 'left_knee', angle: 90, axis: 'flexion' },
      { joint: 'right_knee', angle: 90, axis: 'flexion' },
      { joint: 'left_hip', angle: 45, axis: 'flexion' },
      { joint: 'right_hip', angle: 45, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 150, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 150, axis: 'abduction' },
    ],
    tolerance: 25,
    keyPoints: [
      { joint: 'left_hip', idealAngle: 45, description: '身体充分前屈' },
    ],
    commonMistakes: ['臀部抬起', '呼吸不均匀'],
  },
  {
    id: 'bhujangasana',
    nameCN: '眼镜蛇式',
    nameEN: 'Cobra Pose',
    nameSanskrit: 'Bhujangasana',
    difficulty: 'beginner',
    category: '俯卧',
    description: '俯卧后弯，腿贴地',
    benefits: ['强化背部', '打开胸腔', '改善脊柱灵活性'],
    targetAngles: [
      { joint: 'left_knee', angle: 175, axis: 'flexion' },
      { joint: 'right_knee', angle: 175, axis: 'flexion' },
      { joint: 'left_elbow', angle: 150, axis: 'flexion' },
      { joint: 'right_elbow', angle: 150, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 45, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 45, axis: 'abduction' },
    ],
    tolerance: 20,
    keyPoints: [
      { joint: 'left_knee', idealAngle: 175, description: '双腿伸直贴地' },
    ],
    commonMistakes: ['肩膀耸起', '腰部过度弯曲', '腿部离地'],
  },
  {
    id: 'navasana',
    nameCN: '船式',
    nameEN: 'Boat Pose',
    nameSanskrit: 'Navasana',
    difficulty: 'intermediate',
    category: '坐姿',
    description: 'V形坐姿，腿抬起',
    benefits: ['强化核心', '提高平衡', '增强髋屈肌'],
    targetAngles: [
      { joint: 'left_knee', angle: 175, axis: 'flexion' },
      { joint: 'right_knee', angle: 175, axis: 'flexion' },
      { joint: 'left_hip', angle: 45, axis: 'flexion' },
      { joint: 'right_hip', angle: 45, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 30, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 30, axis: 'abduction' },
    ],
    tolerance: 25,
    keyPoints: [
      { joint: 'left_hip', idealAngle: 45, description: '身体与腿形成V形' },
    ],
    commonMistakes: ['拱背', '腿弯曲', '手臂下垂'],
  },
  {
    id: 'savasana',
    nameCN: '挺尸式',
    nameEN: 'Corpse Pose',
    nameSanskrit: 'Savasana',
    difficulty: 'beginner',
    category: '仰卧',
    description: '仰卧完全放松',
    benefits: ['深度放松', '缓解压力', '恢复精力'],
    targetAngles: [
      { joint: 'left_knee', angle: 175, axis: 'flexion' },
      { joint: 'right_knee', angle: 175, axis: 'flexion' },
      { joint: 'left_hip', angle: 175, axis: 'flexion' },
      { joint: 'right_hip', angle: 175, axis: 'flexion' },
      { joint: 'left_shoulder', angle: 15, axis: 'abduction' },
      { joint: 'right_shoulder', angle: 15, axis: 'abduction' },
    ],
    tolerance: 20,
    keyPoints: [
      { joint: 'left_knee', idealAngle: 175, description: '双腿自然伸直放松' },
    ],
    commonMistakes: ['身体紧张', '呼吸不均匀'],
  },
]

/** 根据 ID 获取标准体式 */
export function getStandardPose(id: string): StandardPose | undefined {
  return STANDARD_POSES.find((p) => p.id === id)
}
